docs(2020-10-28): frontend initiatives
dhis2/notes pull request #137
Opened 2020-10-28 18:05 UTC by varl

2020-10-29 08:26 UTC, HendrikThePendric requested changes
LGTM, apart from two small points being a bit unclear to me.

2020-10-29 08:26 UTC, HendrikThePendric commented on decisions/2020/10/28-frontend-initiatives.md
> +	Porting d2-ui to ui.
Could you elaborate on this a bit more? I'm not quite sure how to interpret these 2 points.

2020-10-29 08:34 UTC, Mohammer5 approved these changes

2020-10-29 08:38 UTC, varl commented on decisions/2020/10/28-frontend-initiatives.md
> +	Porting d2-ui to ui.
Alright, expanded a bit on the context. Does that help?

2020-10-29 09:03 UTC, amcgee approved these changes

2020-11-02 08:41 UTC, HendrikThePendric approved these changes

2020-11-02 08:43 UTC, paschalidi approved these changes

2020-11-03 06:54 UTC, merged